### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Incorrect response JSON

### ISSUE THREAD

**Issue by socialatm** [jdrydn/mocha-axios#6]
`node_modules/mocha-axios/integration.js`
lines 66-69
```js
if (opts.res.data) {
      if (req.responseType === 'json') assert.deepEqual(res.data, opts.res.data, 'Incorrect response JSON');
      else assert.equal(res.data, opts.res.data, 'Incorrect response body');
    }
```
No matter what I include or leave out it always breaks here.
When I comment it out it works as expected.
This program has great potential.
I'm sure it could be operator error too but I wanted to pass it along.
Thanks
Ray

**Comment by jdrydn** [comment]
Your test runner (e.g. [mocha](https://mochajs.org/)) should take the result of the `assert` failure & show you which part of your response doesn't equal as expected.

Could you please include a sample of code so I can see your use-case & provide a sample of the response so I can compare? Also a screenshot of terminal output would be appreciated too!

**Comment by socialatm** [comment]
I think it's an issue on my end. The client males an api call and a token is returned with the response so the request and response never match.

**Comment by jdrydn** [comment]
Ah, makes sense. Have you seen the [`modify`](https://github.com/jdrydn/mocha-axios#modify) extension that's designed to change dynamic values into predictable ones?

**Comment by socialatm** [comment]
I'll look into that `modify` extension. Thanks so much
